version: '3'
services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "127.0.0.1:9001:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: danisbagus
      TZ: Asia/Jakarta
    networks:
      - edagang-product-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    networks:
      - edagang-product-net

volumes:
  mysqldata:
    driver: local

networks:
  edagang-product-net:
    driver: bridge